### ISSUE TITLE
Problem with isntall arriba by conda (samtools libcrypto.so)

### ISSUE THREAD

**Issue by zgtman** [suhrig/arriba#73] opened 2020-07-31 08:45 UTC
Dear all,

I am facing problem to install arriba via conda:

`samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`

There is a few threads to solve this issue - but is works if you install samtools separately NOT in arriba environment:

`conda install samtools openssl=1.1` 

Best,

Paul.

**Comment by zgtman** [comment] 2020-07-31 08:57
I solve problem :
1. install samtools to separate env - `conda install -n samtools_env -c bioconda samtools openssl=1.0`
2. install arriba to another env - `conda install -n arriba_env -c bioconda arriba`
3. go to `$CONDA/envs/arriba_env/lib` and create link from samtools_env such as: `ln -s $CONDA/envs/samtools_env/lib/libcrypto.so.1.0.0 . 
`
and it works to me.

**Comment by suhrig** [comment] 2020-07-31 09:49
Hi Paul,

Thanks for reporting this issue and thank you even more for directly providing a workaround! Conda never ceases to surprise me with new problems ... I hope I will find a fix for this particular problem before the next release of Arriba comes out. I will keep this issue open until then.

Regards,
Sebastian

**Comment by zgtman** [comment] 2020-08-04 12:58
Hi Sebastian, I must absolutely agree with you - Conda surprise me almost every week :) BTW thank you for arriba - great program!

**Comment by suhrig** [comment] 2020-09-11 08:56
Hi Paul,

This issue is all over the net, but I cannot reproduce it. If I use the following commands, everything works as expected:

```
wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.3-Linux-x86_64.sh
bash Miniconda3-py38_4.8.3-Linux-x86_64.sh
eval "$(/tmp/miniconda3/bin/conda shell.bash hook)"
conda install -c conda-forge -c bioconda arriba=1.2.0
```

Suprisingly, the samtools that gets installed in my tests does not even depend on libcrypto:

```
$ which samtools
/tmp/miniconda3/bin/samtools
$ ldd /tmp/miniconda3/bin/samtools
/usr/bin/ldd: line 161: /lib/ld-linux.so.2: No such file or directory
        linux-vdso.so.1 =>  (0x00007ffc461c1000)
        libhts.so.3 => /tmp/miniconda3/bin/../lib/libhts.so.3 (0x00007fa58a5b4000)
        libtinfow.so.6 => /tmp/miniconda3/bin/../lib/libtinfow.so.6 (0x00007fa58a574000)
        libncursesw.so.6 => /tmp/miniconda3/bin/../lib/libncursesw.so.6 (0x00007fa58a537000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fa58a212000)
        libz.so.1 => /tmp/miniconda3/bin/../lib/libz.so.1 (0x00007fa58a1f1000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fa589fd5000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fa589c07000)
        libdeflate.so.0 => /tmp/miniconda3/bin/../lib/./libdeflate.so.0 (0x00007fa589bf6000)
        liblzma.so.5 => /tmp/miniconda3/bin/../lib/./liblzma.so.5 (0x00007fa589bcd000)
        libbz2.so.1.0 => /tmp/miniconda3/bin/../lib/./libbz2.so.1.0 (0x00007fa589bb9000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fa5899b4000)
        /lib64/ld-linux-x86-64.so.2 (0x0000500000000000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fa5897ac000)
```

Can you confirm that you are using samtools from your conda environment and check whether it indeed depends on libcrypto?

I have read that the issue can arise from having the wrong channel priority. In my setup, samtools is pulled from the `bioconda` channel:

```
$ conda list | grep '^samtools'
samtools                  1.10                 h2e538c0_3    bioconda
```

And the channel priority is this: 

```
$ conda config --show channels
channels:
  - conda-forge
  - bioconda
  - defaults
```

What do the above commands show for your setup?

Regards,
Sebastian

**Comment by alespetr** [comment] 2020-09-11 14:01
Dear Sebastian,

Yes of course:

```
(arriba_env) [paul@sheldon]$ ldd /var/anaconda3/envs/arriba_env/bin/samtools
	linux-vdso.so.1 =>  (0x00007fff34ab1000)
	libz.so.1 => /var/anaconda3/envs/arriba_env/bin/../lib/libz.so.1 (0x00007f317baff000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f317b5f7000)
	libbz2.so.1.0 => /var/anaconda3/envs/arriba_env/bin/../lib/libbz2.so.1.0 (0x00007f317badd000)
	liblzma.so.5 => /var/anaconda3/envs/arriba_env/bin/../lib/liblzma.so.5 (0x00007f317bab4000)
	libcurl.so.4 => /var/anaconda3/envs/arriba_env/bin/../lib/libcurl.so.4 (0x00007f317ba24000)
	libcrypto.so.1.0.0 => /var/anaconda3/envs/arriba_env/bin/../lib/libcrypto.so.1.0.0 (0x00007f317b32b000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f317b10f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f317ad41000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f317b8f9000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f317ab39000)
	libnghttp2.so.14 => /var/anaconda3/envs/arriba_env/bin/../lib/./libnghttp2.so.14 (0x00007f317b9fa000)
	libssh2.so.1 => /var/anaconda3/envs/arriba_env/bin/../lib/./libssh2.so.1 (0x00007f317b9b6000)
	libssl.so.1.1 => /var/anaconda3/envs/arriba_env/bin/../lib/./libssl.so.1.1 (0x00007f317b926000)
	libgssapi_krb5.so.2 => /var/anaconda3/envs/arriba_env/bin/../lib/./libgssapi_krb5.so.2 (0x00007f317aaea000)
	libkrb5.so.3 => /var/anaconda3/envs/arriba_env/bin/../lib/./libkrb5.so.3 (0x00007f317aa11000)
	libk5crypto.so.3 => /var/anaconda3/envs/arriba_env/bin/../lib/./libk5crypto.so.3 (0x00007f317a9f2000)
	libcom_err.so.3 => /var/anaconda3/envs/arriba_env/bin/../lib/./libcom_err.so.3 (0x00007f317b91e000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f317a7ee000)
	libkrb5support.so.0 => /var/anaconda3/envs/arriba_env/bin/../lib/././libkrb5support.so.0 (0x00007f317a7df000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f317a5c5000)
```
```
(arriba_env) [paul@sheldon]$ conda config --show channels
channels:
  - conda-forge
  - bioconda
  - defaults
```
```
(arriba_env) [paul@sheldon]$ conda list | grep '^samtools'
samtools                  1.7                           1    bioconda
```

I hope it helps. Right now I have no problem with arriba.

Paul.

**Comment by suhrig** [comment] 2020-09-12 21:04
Thanks, that was helpful. It is indeed that particular samtools version (1.7) that seems to be faulty. When I manually downgrade, I get the same error and can confirm the dependency on libcrypto.

Anyway, this is not an Arriba issue per se and the error should actually not occur if you install Arriba according to the manual. The instructions of the manual cause samtools 1.10 to be installed, where this problem does not exist. My guess is that you have some other bioconda package in your environment that causes samtools to be downgraded to 1.7. Since there is nothing I can do about a faulty bioconda build, I think this issue has to be closed as unfixable. Thanks for the feedback nonetheless. Always appreciated!

**Closed by suhrig** 2020-09-12 21:04 UTC

**Comment by suhrig** [comment] 2020-10-26 12:38
Hi Paul,

I can now reproduce the issue. Since Arriba version 2.0.0, conda preferentially installs the malfunctioning samtools version 1.7. To prevent other users from running into this issue, I have resorted to the following workaround: I modified the bioconda recipe of Arriba require samtools version >=1.9 (because 1.8 was also faulty). This is not an ideal solution, because Arriba runs in principle also with samtools < 1.9, but it is a practical one. The sad news is that when you now install Arriba 2.0.0 using bioconda, it still wants to install the old build with the dependency on samtools>=1.0. Argh! So if you just type `conda install -c conda-forge -c bioconda arriba=2.0.0` the faulty build will be installed; you have to explicitly ask for the new build: `conda install -c conda-forge -c bioconda arriba=2.0.0=hd2e4403_1`. Anyhow, with the next release, this problem will be obsolete, because the next release will come with the 1.9 dependency from the very beginning, such there won't be a risk of installing a faulty build.

Thanks again for reporting,
Sebastian
