### ISSUE TITLE
 Failed to read BGZF block data at offset 

### ISSUE THREAD

**Issue by 6EMNKEY** [suhrig/arriba#184] opened 2023-02-24 10:41 UTC
I have this issue and I can't seem to find its origin, its a samtools error because of the bam not being correctly generated. It did work for all the fastqs that i used but this one and I checked the fastqs and they seem to be fine.

COMMAND I LAUNCHED:

./run_arriba.sh STAR_index_GRCh38_ENSEMBL104 Homo_sapiens.GRCh38.108.chr.gtf Homo_sapiens.GRCh38.dna.primary_assembly.fa database/blacklist_hg38_GRCh38_v2.3.0.tsv database/known_fusions_hg38_GRCh38_v2.3.0.tsv database/protein_domains_hg38_GRCh38_v2.3.0.gff3 10 aml/139BP

RESULT:

/SRR7646939_1.fastq.gz aml/139BP/SRR7646939_2.fastq.gz
+ STAR_INDEX_DIR=STAR_index_GRCh38_ENSEMBL104
+ ANNOTATION_GTF=Homo_sapiens.GRCh38.108.chr.gtf
+ ASSEMBLY_FA=Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa
+ BLACKLIST_TSV=database/blacklist_hg38_GRCh38_v2.3.0.tsv
+ KNOWN_FUSIONS_TSV=database/known_fusions_hg38_GRCh38_v2.3.0.tsv
+ TAGS_TSV=database/known_fusions_hg38_GRCh38_v2.3.0.tsv
+ PROTEIN_DOMAINS_GFF3=database/protein_domains_hg38_GRCh38_v2.3.0.gff3
+ THREADS=10
+ READ1=aml/139BP/SRR7646939_1.fastq.gz
+ READ2=aml/139BP/SRR7646939_2.fastq.gz
++ dirname ./run_arriba.sh
+ BASE_DIR=.
+ STAR --runThreadN 10 --genomeDir STAR_index_GRCh38_ENSEMBL104 --genomeLoad NoSharedMemory --readFilesIn aml/139BP/SRR7646939_1.fastq.gz aml/139BP/SRR7646939_2.fastq.gz --readFilesCommand zcat --outStd BAM_Unsorted --outSAMtype BAM Unsorted --outSAMunmapped Within --outBAMcompression 0 --outFilterMultimapNmax 50 --peOverlapNbasesMin 10 --alignSplicedMateMapLminOverLmate 0.5 --alignSJstitchMismatchNmax 5 -1 5 5 --chimSegmentMin 10 --chimOutType WithinBAM HardClip --chimJunctionOverhangMin 10 --chimScoreDropMax 30 --chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --chimSegmentReadGapMax 3 --chimMultimapNmax 50
+ tee Aligned.out.bam
+ ./arriba -x /dev/stdin -o fusions.tsv -O fusions.discarded.tsv -a Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa -g Homo_sapiens.GRCh38.108.chr.gtf -b database/blacklist_hg38_GRCh38_v2.3.0.tsv -k database/known_fusions_hg38_GRCh38_v2.3.0.tsv -t database/known_fusions_hg38_GRCh38_v2.3.0.tsv -p database/protein_domains_hg38_GRCh38_v2.3.0.gff3
[2023-02-23T15:29:48] Launching Arriba 2.4.0
[2023-02-23T15:29:52] Loading assembly from 'Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa' 
[2023-02-23T15:38:09] Loading annotation from 'Homo_sapiens.GRCh38.108.chr.gtf' 
[2023-02-23T15:50:07] Reading chimeric alignments from '/dev/stdin[E::bgzf_read_block] Failed to read BGZF block data at offset 16572414963 expected 65293 bytes; hread returned 4078
[E::bgzf_read] Read block operation failed with error 4 after 91 of 216 bytes
(total=ERROR: failed to load alignments

**Comment by suhrig** [comment] 2023-02-24 10:53
Is this a reproducible error? Could it be that you are running out of disk space?

**Comment by 6EMNKEY** [comment] 2023-03-02 09:54
yes, I have run it three times, and No it can't be because I have enough disk space for this and a lot more since it is running in a cluster , and also it worked with the other 33 samples. I know this leads to think that the sample is wrong but I have tested it and it works for other programs.

**Comment by suhrig** [comment] 2023-03-03 21:52
> it works for other programs

Are you saying that you ran other programs on the file `Aligned.out.bam` generated by `run_arriba.sh`? If not, can you try the following:

1. Remove all commands after `tee` so that the script exits right after creating the BAM file.
2. Zip the file and share it with me so I can analyze it.

I tried to reproduce this on my end, but it works for me. Probably, a small detail is different in my environment.

**Comment by suhrig** [comment] 2023-03-24 08:06
If you still have interest, I could try to get to the bottom of this. But I need your BAM file, because I cannot reproduce it myself. This looks like either a bug in STAR or in htslib (which Arriba uses for loading BAM files).

**Comment by suhrig** [comment] 2023-05-06 12:50
I'm closing this for now due to lack of user feedback. If you still want to work this out, please reopen the issue.

**Closed by suhrig** 2023-05-06 12:50 UTC
