### ISSUE TITLE
separate IDs of split-reads from those of discordant-reads

### ISSUE THREAD

**Issue by jzjsoil** [suhrig/arriba#45] opened 2020-02-18 14:49 UTC
Hi suhrig,
First, thank you so much for making such a wonderful tool, fast and sensitive.
Secondly, I have a suggestion in the column of read_identifiers in the result file. In this column, could you please separate IDs of split-reads from IDs of discordant-reads? so save them in two separate columns, instead of in a single column. Also the IDs of duplicates and mismatches are better to list separately since they are not real supporting evidence.

Thank you.
Z

**Comment by suhrig** [comment] 2020-02-18 23:51
Hi jzjsoil,

I'm glad you find the tool useful. Incidentally, the list of read IDs is sorted by split_reads1, split_reads2, and discordant_mates, albeit it is not evident where the list of split reads ends and where the list of discordant mates starts. However, I am a bit reluctant to changing the output format of Arriba. I would like to keep the format stable for as long as possible, because every change requires adaptations to existing pipelines which make use of Arriba. This would be an inconvenience for current users and should therefore only be considered when there is a high demand for the format change. If you absolutely need this information, I could provide you with a patch of Arriba's source code that splits the read ID list over multiple columns as suggested by you. This isn't too complicated.

Regards,
Sebastian

**Comment by jzjsoil** [comment] 2020-02-19 02:26
Hi Sebastian,
Thank you for our reply, and your concern is very understandable. I think not too many people ask for such details.
It’s great if you can share the patch with me.

Best,
Zhijie

**Comment by suhrig** [comment] 2020-02-19 11:31
Hi Zhijie,

Here is a patched version of `output_fusions.cpp` which does what you asked for: [output_fusions.cpp.zip](https://github.com/suhrig/arriba/files/4224789/output_fusions.cpp.zip)

Replace the original file in the `source` folder of Arriba an recompile by running `make`.

Regards,
Sebastian

**Comment by jzjsoil** [comment] 2020-02-19 16:04
Hi Sebastian,
Thank you so much for sharing the file.
But are you sure this is the right file. I recompiled with the file you sent me, and the column of read_identifiers is empty even though the count of split-reads and discordant_mates is greater than 0 (as attached).

Best,
Zhijie

**Comment by suhrig** [comment] 2020-02-19 16:38
Did you run Arriba with the parameter `-I`? Read IDs are only reported when this parameter is given.

**Comment by jzjsoil** [comment] 2020-02-19 17:53
My bad. I forgot this switch.
I reran the program. In the new result file, beside the column of read_identifiers, I do not see any new columns. And IDs in this column are connected by comma. Did I miss something?

Thanks,
Zhijie

**Comment by jzjsoil** [comment] 2020-02-19 19:24
Hi Sebastian,
It works now!
It turns out I have to recompile all cpp in source folder.

Thank you so much for your help.

BTW, what’s the major difference between v1.2.0 and v.1.1.0 (which I am using now)?

Best,
Zhijie

**Comment by suhrig** [comment] 2020-02-19 22:34
I'm glad you figured it out.

Major changes between versions are listed on the [releases page](https://github.com/suhrig/arriba/releases).

**Comment by jzjsoil** [comment] 2020-02-20 15:11
Hi Sebastian,
Thank you for pointing out the release page.

Since we already processed our many samples by Arriba with the standard output, before we rerun Arriba on these samples with the alternative output, I want to confirm one thing with you.

You mentioned earlier that in the standard output, the reads in the column of reads_identifiers are ordered by split_reads1, split_reads2 and discordant_mates. I checked and found out that duplicates will be present either before or after discordant_mates if duplicates are reported. So based on the number of split_reads1, split_reads2 and discordant_mates it’s difficult to parse out these reads solely from reads_identifiers column if duplicates are also reported. Is that true?

So based on the above description, if we can to separate split_reads from discordant_names, we have to rerun Arriba with the alternative output.

Best,
Zhijie

**Comment by suhrig** [comment] 2020-02-20 17:09
You're right. I can confirm that in the original output format duplicates and non-duplicate reads are interspersed. Segregating them is impossible.

To be clear: The patch I sent to you puts all discarded reads in a separate column, regardless of the type of filter that discarded them. So the column does not only contain duplicates, or also contains reads discarded due to having too many mismatches or other reasons. Since in your initial request, you asked such reads to be separated as well, I wrote the patch that way. If you only want duplicates to be separate then the patch needs to be adjusted slightly.

**Comment by jzjsoil** [comment] 2020-02-20 17:41
Hi Sebastian,
The patch you shared with me serves me alright.
Since I already ran Arriba on many samples with the standard output, before reruning Arriba on these samples to generate the alternative output I was wondering if I could make use of read_identifiers. 

If duplicates are mixed with non-duplicate just let you confirmed, it’s not possible for me to parse out split-reads and discordant_reads from read_identifiers.

So I guess the only option for me now is to rerun Arriba with the new patch.

Thanks,
Zhijie

**Comment by suhrig** [comment] 2020-10-10 19:10
Hi Zhijie, I'm closing this issue, since everything has been discussed as far as I can tell. You can reopen it in case of further questions. Regards, Sebastian

**Closed by suhrig** 2020-10-10 19:10 UTC
