### ISSUE TITLE
the fusion can not be detected by Arriba

### ISSUE THREAD

**Issue by wuyingkongsuifeng74** [suhrig/arriba#64] opened 2020-05-28 01:30 UTC
The reference standard is quantitative analysis of different cell lines by ddPCR
![reference standard](https://user-images.githubusercontent.com/66003014/83088198-a8d8bf80-a0c5-11ea-884a-8e33d6a8c058.png)

The Fig  is the demonstrate the detail of these fusion.  The left panel is the softclip reads around breakpoint of the ALK gene，the right panel is the softclip reads around breakpoint of the NPM1 gene
![ALK-NPM1](https://user-images.githubusercontent.com/66003014/83087575-2c91ac80-a0c4-11ea-9a01-0180de3ad34e.png)

**Comment by suhrig** [comment] 2020-05-28 06:57
Thanks for the clarification and the screenshot. I understand now. It seems the problem is that STAR is unable to map these reads, because they are multimapping chimeric reads. STAR currently does not report these alignments. I submitted a pull request to eliminate this short-coming to the developer of STAR a few months ago. It has not been incorporated in the main code yet. Using my patched version of STAR and a (not yet released) enhanced version of Arriba, this particular fusion should be detected as well. So stay tuned for the next release of STAR and Arriba.

**Comment by ahy1221** [comment] 2020-08-29 06:09
Hi @suhrig , it seems that the current release of STAR has added an option "--chimMultimapNmax " to detect multiple mapping chimeric reads. 
However, the output for the new algorithm is not compatible with Arriba. It only outputs the chimeric alignment results to the Chimeric.junction.out file but not the Chimeric.out.sam. 
I was wondering that is possible to update Arriba to use the new chimeric detecting algorithm of STAR? 
In my view, I think one of the main advantages of Arriba is that it can detect intergenic fusion, which is really useful for virus integration analysis!

Thank you!

Yao He

**Comment by suhrig** [comment] 2020-08-29 07:20
> I was wondering that is possible to update Arriba to use the new chimeric detecting algorithm of STAR?

Enabling Arriba to make use of mulit-mapping chimeric reads requires two steps: adapting the code of Arriba and enhancing STAR to output multi-mapping chimeric reads in the standards-compliant SAM/BAM format rather than it's proprietary Chimeric.out.junction format, because Arriba cannot use the latter. Both steps are in the workings: I am currently working on Arriba 2.0.0, which will be able to handle multi-mapping chimeric reads, and I have submitted a pull request to the developer of STAR, which he promised to incorporate soon. So stay tuned. It shouldn't last long anymore until this capability is implemented.

**Comment by ahy1221** [comment] 2020-08-30 03:32
Thank you! Looking forward to the Arriba 2.0

**Comment by suhrig** [comment] 2020-10-10 18:22
Hi Yao He,

[Release 2.0.0 is out](https://github.com/suhrig/arriba/releases/tag/v2.0.0). With this, the NPM1-ALK fusion should be detected. Note that you need the latest version of STAR (2.7.6a) and the parameter `--chimMultimapNmax 50` to detect fusions supported by multi-mapping reads. I'm closing this as resolved. Feel free to reopen if you still have issues.

Regards,
Sebastian

**Closed by suhrig** 2020-10-10 18:22 UTC
