### ISSUE TITLE
Missing most of IGH fusions

### ISSUE THREAD

**Issue by ndaniel** [suhrig/arriba#106] opened 2021-03-15 12:37 UTC
It looks like Arriba is missing most of the time most of IGH fusions.

For example, it is very well known in published scientific literature that MUTZ-5 cancer cell line harbors IGH-CRLF2 fusion, as shown here:
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3412346/ , and
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4450636/, and
- https://www.pnas.org/content/107/1/252 , and
- https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0220026 , and
- https://www.nature.com/articles/leu2012101 , and
- etc.

Other fusion callers, like FusionCatcher and CICERO are able to find this fusion in MUTZ-5 cell line, using this RNA-seq data:

- ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR861/006/SRR8615686/SRR8615686_1.fastq.gz 
- ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR861/006/SRR8615686/SRR8615686_2.fastq.gz  
 
but Arriba v2.1.0 is totally missing it.

**Comment by suhrig** [comment] 2021-03-15 14:23
Hi Daniel,

Thanks for sending me a link to the test sample. RNA-Seq data from samples with IGH-CRLF2 fusions are hard to find. I will have a look at it.

> It looks like Arriba is missing most of the time most of IGH fusions.

Sounds like you have run Arriba on more samples than just the MUTZ-5 cell line to come to this conclusion. Where do I find these samples? The papers you linked do not provide RNA-Seq data if I'm not mistaken. Without the raw data it is hard to investigate how big the issue is and what the root cause is.

Regards,
Sebastian

**Comment by ndaniel** [comment] 2021-03-15 19:05
@suhrig 

> The papers you linked do not provide RNA-Seq data if I'm not mistaken. 

The paper which I provided, show that MUTZ5 cell line harbors IGH-CRLF2 fusion. There is no claim in my message that those papers contain RNA-seq data.

> Without the raw data it is hard to investigate how big the issue is and what the root cause is.

I provided here a very nice example, backed up by raw RNA-seq data, of an IGH fusion which Arriba misses. This should give a very good start.

>Thanks for sending me a link to the test sample. 

Welcome!

> RNA-Seq data from samples with IGH-CRLF2 fusions are hard to find. I will have a look at it.

True but a simple scientific literature review helps a lot.

**Comment by suhrig** [comment] 2021-03-15 20:08
> The paper which I provided, show that MUTZ5 cell line harbors IGH-CRLF2 fusion. There is no claim in my message that those papers contain RNA-seq data.

I see. I thought you pointed me to a collection of papers with sequencing data of such cases. I did not see a point in linking a whole bunch of them, other than to provide sources from where to get data. I mean, a single paper would have sufficed to inform me about the mere existence of the fusion.

> but Arriba v2.1.0 is totally missing it.

When I run Arriba myself on that sample, it reports the fusion. These are the breakpoints (hg19):

```
14:106329465 -> annotated as IGHJ6
X:1347560    -> annotated as an enhancer hijacking event with a breakpoint 15kb upstream of CRLF2
```

So it must be something with the way that you use the tool that causes the fusion to be missed. Did you use the commands from the [user manual](https://arriba.readthedocs.io/en/v2.1.0/quickstart/) to setup and run Arriba? I used the precise instructions stated there (docker) and Arriba found the fusion.

> True but a simple scientific literature review helps a lot.

Believe me, I searched the literature a lot for more examples than just the MUTZ-5 cell line from CCLE. I could not find any. I would be grateful if you could point me to some more. Do you know of any more?

**Comment by ndaniel** [comment] 2021-03-17 11:06
So I run arriba v2.1.0. and it is missing IGH-CRLF2 fusion in MUTZ5 cell line using this raw RNA-seq data that is publicly available:

- ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR861/006/SRR8615686/SRR8615686_1.fastq.gz
- ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR861/006/SRR8615686/SRR8615686_2.fastq.gz

I run arriba like this:
```
../run_arriba.sh ../STAR_index_GRCh37_RefSeq_hg19/ ../RefSeq_hg19.gtf ../GRCh37.fa ../database/blacklist_hg19_hs37d5_GRCh37_v2.1.0.tsv ../database/known_fusions_hg19_hs37d5_GRCh37_v2.1.0.tsv ../database/protein_domains_hg19_hs37d5_GRCh37_v2.1.0.gff3 32  SRR8615686_1.fastq.gz SRR8615686_2.fastq.gz 
```

and `fusions.tsv` looks like this (here are the only first 10 columns):
```
#gene1	gene2	strand1(gene/fusion)	strand2(gene/fusion)	breakpoint1	breakpoint2	site1	site2	type	split_reads1
IKZF1	FIGNL1	+/+	-/+	7:50367353	7:50505862	CDS/splice-site	3'UTR	deletion/read-through/5'-5'	286
PAX5	ZCCHC7	-/+	+/+	9:36929048	9:37187488	intron	intron	deletion/read-through/3'-3'	58
PRKAA1	CARD6(39713),C7(14430)	-/-	./+	5:40798165	5:40895169	CDS/splice-site	intergenic	inversion	20
PHF11	DHRS12	+/+	-/+	13:50095617	13:52351366	intron	CDS	deletion/5'-5'	38
SETDB2-PHF11	DHRS12	+/+	-/+	13:50095617	13:52351366	intron	CDS	deletion/5'-5'	38
TSC22D1	MIR8079(74958),SERP2(102492)	-/-	./-	13:45010640	13:44845294	CDS/splice-site	intergenic	deletion/read-through	21
RB1	LINC00462(66794),CYSLTR2(6234)	+/+	./+	13:48955579	13:49221831	CDS/splice-site	intergenic	deletion/read-through	11
LRP6	LOC440084(32915),LINC01252(28437)	-/-	./-	12:12397195	12:11672527	intron	intergenic	deletion	11
CEP20	CEP20(16058),ABCC1(44955)	-/-	./-	16:15977865	16:15998518	CDS/splice-site	intergenic	duplication	9
TLK2	FAM157B	+/+	+/+	17:60637487	3:197907626	CDS/splice-site	exon/splice-site	translocation	1
TLK2	FAM157A	+/+	+/+	17:60637487	3:197907626	CDS/splice-site	exon/splice-site	translocation	1
CCDC26	LINC00976(136388),LINC00977(114078)	-/-	./-	8:130587128	8:130114635	exon/splice-site	intergenic	deletion	1
IKZF1	IKZF1(25341),FIGNL1(6879)	+/+	./+	7:50367353	7:50498139	CDS/splice-site	intergenic	deletion/read-through	89
UPK3BL1	RASA4	-/-	-/-	7:102279161	7:102251589	CDS/splice-site	CDS/splice-site	deletion/read-through	4
POLR2J2	RASA4	-/-	-/-	7:102279161	7:102251589	3'UTR/splice-site	CDS/splice-site	deletion/read-through	4
POLR2J2	RASA4	-/-	-/-	7:102306524	7:102251589	3'UTR/splice-site	CDS/splice-site	deletion/read-through	0
STAM(28823),TMEM236(6556)	TMEM236	./+	+/+	10:17787644	10:18060292	intergenic	CDS/splice-site	deletion/read-through	2
DENND3	DENND3	+/.	+/.	8:142152030	8:142153630	intron	intron	duplication	7
ANXA11	PNLIPRP1(1460),PNLIPRP2(10318)	-/-	./+	10:81910977	10:118370147	3'UTR	intergenic	inversion	0
GEN1(11281),MSGN1(16233)	SMC6	./-	-/-	2:17981494	2:17927218	intergenic	5'UTR/splice-site	deletion/read-through	3
STEAP1B(10914),LOC100506178(52141)	HLA-DPA1	./+	-/-	7:22550815	6:33041414	intergenic	5'UTR	translocation	4
IKZF1	FIGNL1(7817),DDC(213)	+/+	./+	7:50367353	7:50525921	CDS/splice-site	intergenic	deletion/read-through	5
TSC22D1	SMIM2(24514),MIR8079(10358)	-/-	./-	13:45147299	13:44759907	CDS/splice-site	intergenic	deletion/read-through	1
SLC25A6(1533),LINC00106(3379)	ASMTL-AS1	./.	+/.	X:1512539	X:1736735	intergenic	intron	duplication	0
POLR1E	POLR1E(963),FBXO10(6232)	+/.	./.	9:37365590	9:37504657	intron	intergenic	inversion	1
GADD45B	ATP8B3	+/-	-/-	19:2477011	19:1800448	intron	CDS/splice-site	deletion/3'-3'	1
TUBB4B	TUBB	+/+	+/+	9:140136281	6:30690695	CDS/splice-site	CDS/splice-site	translocation	0
TUBB4B	TUBB	+/+	+/+	9:140136281	6:30690695	CDS/splice-site	CDS/splice-site	translocation	0
C12orf4	FGF6	-/-	-/-	12:4596937	12:4551233	3'UTR	intron	deletion/read-through	3
BTG1	DCN(655403),LINC01619(146755)	-/-	./-	12:92539164	12:92231997	CDS/splice-site	intergenic	deletion/read-through	1
SPRY1	LINC01091	+/+	+/+	4:124319668	4:124573942	5'UTR/splice-site	exon/splice-site	deletion/read-through	0
SPATA48	ZPBP	+/-	-/-	7:50156849	7:50121495	intron	CDS/splice-site	deletion/read-through/3'-3'	3
TNS1-AS1(17485),RUFY4(24834)	TNS1	./-	-/-	2:218874823	2:218784959	intergenic	5'UTR/splice-site	deletion/read-through	1
GPR141(77608),NME8(27154)	NME8	./+	+/+	7:37861045	7:37923905	intergenic	CDS/splice-site	deletion/read-through	1
FIGNL1	SPATA48(144287),IKZF1(521)	-/-	./-	7:50505861	7:50343139	3'UTR	intergenic	deletion/read-through	0
NR3C1(237185),MIR5197(7163)	HMHB1	./+	+/+	5:143052262	5:143200045	intergenic	CDS/splice-site	deletion/read-through	4
SYTL2	SYTL2(42701),CCDC83(1523)	-/.	./.	11:85469112	11:85564903	5'UTR	intergenic	deletion/read-through	1
SLC8A1	THUMPD2(138177),SLC8A1-AS1(181)	-/-	./-	2:40332049	2:40144593	3'UTR	intergenic	deletion/read-through	1
LINC00692(638673),LRRC3B(110438)	LRRC3B	./+	+/+	3:26553859	3:26751004	intergenic	5'UTR/splice-site	deletion/read-through	0
TMSB15B-AS1	RAB9B	-/-	-/-	X:103172790	X:103082010	exon	intron	deletion/read-through	0
TVP23A(42277),CIITA(16127)	TVP23A	./-	-/-	16:10954928	16:10869404	intergenic	5'UTR/splice-site	deletion/read-through	0
HTR1F	HTR1F(14516),CGGBP1(43596)	+/+	./+	3:87871274	3:88057504	5'UTR/splice-site	intergenic	deletion/read-through	1
NECAP1	SEC24B	+/+	+/+	12:8242895	4:110394160	CDS/splice-site	CDS/splice-site	translocation	1
CHM	BCL11A	-/-	-/-	X:85282495	2:60679801	CDS/splice-site	CDS/splice-site	translocation	0
SLC7A5	CBFA2T3	-/-	-/-	16:87885330	16:88968064	CDS/splice-site	CDS/splice-site	duplication	1
```
Here attached is the full [fusions.tsv]((https://github.com/suhrig/arriba/files/6155791/fusions.txt) file.

**As one can see clearly IGH@-CRLF2 fusion is missing totally!**

Arriba has been installed from GitHub and the indexes built using this command `./download_references.sh GRCh37+RefSeq`.

STAR version is 2.7.8a.

For some reason the last step arriba is trying to sort the bam file and is crashing with some error regarding samtools. Samtools is v1.11.

Regarding IGH fusions they are challenging. Out there are other very challenging types of fusions also which have not been mentioned here at all.

**Comment by suhrig** [comment] 2021-03-18 13:38
> ./download_references.sh GRCh37+RefSeq

This explains our differing observations. RefSeq has less comprehensive annotation than GENCODE, which is why the latter is recommended to be used for Arriba as mentioned in the quickstart guide. For most cases, users are free to choose whatever annotation they prefer, because it makes little difference. But for some special fusions the recommended parameters should be used, or else users will have to accept reduced sensitivity. Run the tool with GENCODE19 as stated in the manual and you should see the fusion.

> For some reason the last step arriba is trying to sort the bam file and is crashing with some error regarding samtools.

This is nothing to worry about. It is more of an informational message. In contrast to most fusion detection tools, the alignments generated by Arriba are reusable, because they are more or less a standard STAR alignment. They can be used for other common purposes, such as expression quantification, analysis of alternative splicing, lookup of allele-specific expression etc. This way, fusion detection using Arriba effectively only incurs a few minutes of CPU time, rather than many hours like other fusion detection tools.

If the script detects that samtools is installed, it sorts and indexes the alignments before completing for the user's convenience, because most downstream analyses require sorted alignments. If samtools cannot be found, the alignments are returned unsorted. The sorting step is independent from the fusion detection and actually a waste of CPU time if you are only interested in fusion calls.

> Samtools is v1.11

Is it in your `$PATH` environment variable? If yes, what happens when you type `samtools --version-only`?

**Comment by ndaniel** [comment] 2021-03-19 08:16
Hi @suhrig 

>    Samtools is v1.11
> Is it in your $PATH environment variable? If yes, what happens when you type samtools --version-only?

Yes, it is.

The exact error from arriba that I get is this:
```
++ samtools --version-only
+ [[ 1.11+htslib-1.11 =~ ^1\. ]]
+ samtools sort -@ 32 -m 4G -T tmp -O bam Aligned.out.bam
samtools sort: couldn't allocate memory for bam_mem
```

**Comment by suhrig** [comment] 2021-03-19 13:48
> It looks to me that -m 4G is memory per thread which in this case the total memory is 32 * 4G = 128G. But here in my case the server has 64G RAM and not 128G. Right?

Yes, the specification is per thread. I wish samtools allowed the specification to be in total. This would be so much more manageable.

> Probably this could be fixed by replacing -m 4G with -m $MEMO where:

Thanks for the code snippet. This can be a solution. I try to keep the script simple, though. It's main purpose is to give users an idea how Arriba and STAR interact with each other, such that they can incorporate it into their own pipeline. It should be easy to grasp and therefore lacks everything that goes beyond essential functionality. I don't want to scare people off with what they may perceive as cryptic awk one-liners. (Although I'm a big fan of awk myself.)

If you plan to put your `$MEMO` line in the script in place of the hard-coded 4G, be sure to use `MemFree` rather than `MemTotal`. And add some buffer, too. Otherwise, you run the risk of overloading your machine.

Maybe I will replace the static 4G with something like STAR_MEMORY_FOOTPRINT / THREADS. The code would still be easy to read and the memory requirements would be more or less the same for both alignment and sorting, which makes it quite predictable. This is nice in case you want to launch the script on a HPC cluster, where you typically have to specify an upper memory limit before lauchning a job and cannot just consume all `MemFree`.

**Comment by suhrig** [comment] 2021-03-20 22:30
I analyzed some more CCLE samples harboring IGH translocations besides MUTZ-5. I collected as many as I could find with reasonable effort. Basically, I [searched for the keywords `IGH` and `CCLE` in Cellosaurus](https://web.expasy.org/cgi-bin/cellosaurus/search?input=ccle%20igh) and noted down all cell lines reporting an IGH translocation in the `Sequence variations` attribute. Moreover, I downloaded the [SvABA structural variant calls from DepMap](https://depmap.org/portal/download/all/?release=CCLE+2019&file=CCLE_translocations_SvABA_20181221.xlsx) and extracted cell lines reported to harbor a structural variant involving IGH. In the following comparison, I only counted translocations listed in one of these two sources, because the ground truth is only known about these fusions.

| cell line | accession | IGH translocation | source | Arriba | FusionCatcher |
|-----------|-----------|-------------------|--------|--------|---------------|
| OCI-Ly3 | SRR8615263 | IGH-SPIB | Cellosaurus | found | found |
| KMS11 | SRR8615354 | IGH-WHSC1 | DepMap | found | found |
| SU-DHL-6 | SRR8615369 | IGH-BCL2 | Cellosaurus | found | found |
| ST486 | SRR8615373 | IGH-MYC | Cellosaurus | found | found |
| SU-DHL-4 | SRR8615378 | IGH-BCL2 | Cellosaurus | found | found |
| LP-1 | SRR8615397 | IGH-WHSC1 | Cellosaurus | found | found |
| SK-MM-2 | SRR8615503 | IGH-CCND1 | Cellosaurus | not found | not found |
| REC1 | SRR8615594 | IGH-CCND1 | DepMap | found | found |
| OPM2 | SRR8615877 | IGH-WHSC1 | DepMap | found | found |
| DB | SRR8615952 | IGH-BCL2 | DepMap | not found | not found |
| Daudi | SRR8615961 | IGH-MYC | Cellosaurus | not found | not found |
| RAJI | SRR8615972 | IGH-MYC | Cellosaurus | found | found |
| A3/KAW | SRR8616021 | IGH-17:56408674 | DepMap | found | found |
| MM1.S | SRR8616070 | IGH-MYC | DepMap | not found | not found |
| MM1.S | SRR8616070 | IGH-MAF | DepMap | found | found |
| CA46 | SRR8616193 | IGH-MYC | Cellosaurus | found | found |

As you can see, Arriba performs equally well as FusionCatcher. Together with the analysis of the TCGA-DLBC cohort in [our paper](https://genome.cshlp.org/content/31/3/448/F2.expansion.html), I hope you find it convincing that Arriba is not at all bad at detecting IGH translocations and probably deserves to be mentioned just as much as FusionCatcher or CICERO in that regard. I encourage you to reconsider your opinion in case you jumped to early conclusions based on the FusionCatcher dataset (which is not an ideal benchmarking dataset as explained in issue #47) or based on running Arriba with non-recommended parameters on the MUTZ-5 sample.

**Comment by suhrig** [comment] 2021-03-26 16:35
I think everything has been clarified. I'm closing this issue.

**Closed by suhrig** 2021-03-26 16:35 UTC

**Comment by ndaniel** [comment] 2021-03-27 09:40
@suhrig 

The table regarding CCLE and expasy and Depmap looks good!
The only comment I have there is that probably it would be great to specify the gene annotation that you used. Arriba offers lots of choices and as you have seen when one chooses other gene annotations the results are totally different. You saw that in my hands the results were different than in your hands. Please, take this as a gently suggestion!

Actually, I run a lot FusionCatcher on HPA and I am aware of your findings. The challenge there is that is no ground truth there. I mean  that there is no proof that those IGH translocations are indeed **not** there. Personally, I am not sure that they are artifacts either. The normal thinking regarding fusion genes does not hold for IGH translocations. I contacted the authors of HPA they were not sure either if indeed those samples contain IGH translocations due to the persons from whom the tissues were collected were pretty old. On top of this there are known the oncogenic fusions can be found in healthy persons before that person gets sick. Look in Google for **preleukemic fusion genes**!

**Comment by suhrig** [comment] 2021-03-28 09:48
> it would be great to specify the gene annotation (version/database)

I will put a note in the quickstart guide to inform users about these shortcomings of RefSeq. Other than that, it should not matter too much which specific version of the assembly/annotation, because Arriba's predictions are fairly stable w.r.t. the detection of driver fusions. As long as you don't use RefSeq to detect IGH translocations, you should be fine, because it is the only annotation that lacks information IGH locus. Users who are interested in B-cell malignancies would probably not want to use RefSeq anyway. They will want to use a gene model with thorough annotation of the IGH locus, because this locus is so relevant to the disease.

> preleukemic fusion genes

The samples from the Human Protein Atlas are composed of two batches: ERR315329-315493 and ERR579133-579139. So there are two explanations for FusionCatcher's predictions:

1. Your narrative: Three out of three samples from the second batch contain preleukemic clones - multiple clones per sample actually, since FusionCatcher reports several hallmark aberrations of B-cell malignancies in each sample. Yet none of the 20 samples of the first batch contain preleukemic clones harboring hallmark aberrations.

2. My narrative: The second batch uses a library preparation protocol that is more prone to artifacts in highly expressed genes and FusionCatcher fails to filter this type of artifact.

There may be no proof that the translocations are not there, but Occam's razor favors the second explanation, as it is much simpler. I mean, what are the odds that all samples from one batch, but no samples from another batch harbor hallmark aberrations of B-cell malignancies? The second explanation is also reconcilable with the observation that FusionCatcher predicts translocations between IGH and a range of highly expressed house-keeping genes such as ribosomal genes or translation factors across many samples. All of this can be explained by one simple rule: FusionCatcher fails to remove lib prep-mediated artifacts.

Even if FusionCatcher's predictions were true in the samples from the Human Protein Atlas. How could a user possibly trust FusionCatcher's predicted IGH hallmark translocations if it predicts IGH translocations with basically anything that is expressed at a high level? As explained in my previous message, oncogenes are likely to be expressed at a high level in malignant tissue, because they are drivers of cancer. So if high expression is a major determinant of whether FusionCatcher predicts a fusion or not, then there is a high risk that the tool will make a false positive call.

**Comment by ndaniel** [comment] 2021-03-29 07:01
Some quick comments.

**Absence of evidence is not evidence of absence**. This means that there is **no** evidence whatsoever that those datasets from HPA do not contain the IGH fusions. 

FusionCatcher predicts based on the data that there are IGH fusions but Arriba predicts that there are no IGH fusions. These are predictions which need to be further validated in the wetlab. One needs to wait until these predictions are valdiated in the wetlab. That is it.

I have never heard of Occam's razor being used for justifying **Absence of evidence is evidence of absence**.

The common knowledge is the opposite which is **Absence of evidence is NOT evidence of absence**.

[Google says](https://www.championingscience.com/2019/03/15/everything-should-be-made-as-simple-as-possible-but-no-simpler/) that  Eistein said something along the line "Everything should be made as simple as possible, but no simpler". In this case I think that your explanation makes the things way too simple and goes against the "no simpler" part.

IGH translocations are found a lot in lymphomas and not only in leukemias. Regarding the pre-leukemic fusions, I was referring to the more general idea that oncogenic fusion genes in general can be found in healthy tissues/people and it will take some time until those people will display the disease. Usually these are biomarkers, which show up way before the disease sets in. For example the famous fusion gene SLC45A3-ELK4 is considered oncogenic fusion even that is found over and over again in healthy tissues/prostates (in different published scientific articles [here](https://europepmc.org/article/med/29100211) and [here](https://europepmc.org/article/med/29100211)). So here  is not surprise that different fusion callers and researchers will have different opinions if such fusions should be reported or not. In FusionCatcher's case it will be reported and let the researcher decide.

**Comment by suhrig** [comment] 2021-03-29 15:17
Occam's razor is applicable. There is a simple explanation ("FusionCatcher is susceptible to a batch effect") and a complex explanation ("all donors of batch 1 are void of hallmark IGH translocations and all donors of batch 2 harbor hallmark IGH translocations"). Without any further evidence, you should favor the simpler one.

> Absence of evidence is NOT evidence of absence

Here, absence of evidence really is useful information: FusionCatcher reports absence of evidence of hallmark IGH translocations in 20/20 samples from batch 1 and presence of evidence of hallmark IGH translocations in 3/3 samples from batch 2. Fisher's exact test tells you that the distribution of positive and negative cases is significantly associated with batches - which is strong evidence of a batch effect. The best argument one can make for FusionCatcher in this situation is that batch 1 may have some unique property that makes detection of hallmark IGH translocations very difficult, which would explain why all samples from this batch are reported to be negative. However, I find it more likely that batch 2 is prone to lib prep-mediated artifacts, because this is very common for RNA-Seq libraries, and that FusionCatcher reports lib prep-artifacts as if they were true fusions in all samples from this batch.

> researchers will have different opinions if such fusions should be reported or not. In FusionCatcher's case it will be reported and let the researcher decide.

This is a sensible practice. However, FusionCatcher should not report false positives, because there is nothing to debate about the relevance of false positives. These predictions look like false positives, because they are batch-specific.

Here are some more observations suggesting that FusionCatcher produces false positive calls with highly expressed genes: I selected the CCLE samples with the highest expression of the IGH locus, but only from cell lines that are not B-cell malignancies. The top three were: SRR8615893_DMS-79, SRR8616161_NCI-H526, and SRR8615518_MKN1. The first two ones are small cell lung cancer, the third one is gastric cancer. It would not make a lot of sense to find IGH translocations in these samples (other than passenger events, and even then only very rarely). But FusionCatcher predicted one of them (MKN1) to harbor a hallmark aberration of a B-cell malignancy, namely IGH-DUX4. Now, it could be that the sample really harbors this fusion by coincidence as a passenger event. There is no evidence that disproves this. But what are the chances? Very slim I would say. The more likely explanation is that FusionCatcher has a problem with highly expressed genes and tends to call hallmark fusions too easily. (My guess is that its whitelist is too sensitive.)

Also, how do you explain FusionCatcher's predictions of IGH translocations involving highly expressed house-keeping genes across a range of samples? Are you really convinced they are true? They are the best example for lib prep artifacts.

I also noticed that FusionCatcher calls translocations involving the T-cell receptor locus "TRA@" in all three of the above samples. Although this is not strictly on topic, it is related, because this locus is similarly hard to deal with w.r.t. fusion detection as the IGH locus. So in a way, this is yet another indication of a specificity problem of FusionCatcher with tricky loci such as IGH. In contrast, Arriba called neither IGH nor TCR translocations in these samples, which makes sense biologically.
