### ISSUE TITLE
Gene coordinates in Gencode19

### ISSUE THREAD

**Issue by erprateek** [suhrig/arriba#59] opened 2020-04-28 05:10 UTC
Hi Sebastian,

This is more so an issue on the gencode19 side rather than on arriba's side but wanted to post it here in case anyone else faces this problem. I came across a rather interesting case where for the same breakpoint, I was getting 2 fusions reported by Arriba. The two fusions had first gene partner as the same but 2 different 3' partners. I went down the rabbit hole trying to find out why this was happening and came to a conclusion that this is an error on the GENCODE19 part.

Genes affected: NOL12 and TRIOBP.
Issue: 
- NOL12 coordinates: **Start:** 38077679 **End** 38170137
- TRIOBP coordinates **Start** 38093010 **End** 38172563

They are on the same chromosome 22. The worst part is: this does not happen at just the 'gene' Feature level but also the underlying features too.

**Comment by erprateek** [comment] 2020-04-28 05:10
I checked gencode33 and found that this issue is not there anymore

**Comment by suhrig** [comment] 2020-04-29 12:09
Indeed an error with GENCODE. I have seen this with a number of genes - some of them even affect highly relevant genes: GENCODE 19 annotates the oncogenic fusion genes FIP1L1-PDGFRA and GOPC-ROS1 as normal transcript isoforms! I hard-coded some of these transcripts in Arriba to be removed. Otherwise, Arriba would never report them, since it would consider them as normal. I can confirm that these errors have been fixed with more recent versions of GENCODE.

**Comment by erprateek** [comment] 2020-04-29 22:01
Note that Arriba handles this situation gracefully and reports both the genes as the candidate fusion partners. Nicely done!

**Closed** 2020-07-15 00:48 UTC
