### ISSUE TITLE
enhance sensitivity with possibly more false positives

### ISSUE THREAD

**Issue by khestir** [suhrig/arriba#147] opened 2022-03-11 00:08 UTC
We are interested in detecting human viral fusions. To maximize sensitivity of detection, we are using the parameters 

-v viral_contig_names
-f top_expressed_viral_contigs,low_coverage_viral_contigs,multimappers,merge_adjacent
-T 10
-c 0.001
-E 0.9

We created simple paired-end fastq files containing synthetic fusion events between human genomic regions and viral contigs. With above parameters, we are able to recover about 20% of the fusion reads in the fastqs. We are not concerned about false positives at the moment and trying to enhance sensitivity. Do you have any advice such as arriba command line options or STAR command line options?

**Comment by suhrig** [comment] 2022-03-11 16:23
You are on the right track. The way how I approach a situation where I want to boost sensitivity is to look at the discarded file, find out which filters caused an expected event to be rejected, and then tweak the filter parameters or disable the filter altogether. It seems this is what you have done so far. I don't recommend disabling the `merge_adjacent` filter, though. It does not really discard any events; it merely merges similar breakpoints (as a result of alternative alignment) into one, which actually boosts sensitivity, because the overall number of supporting reads of a breakpoint increases. You can also try disabling the filter `min_support`, such that events with even just a single supporting read will be reported (the default is at least two). And instead of increasing the value of `-E`, you can completely disable it using `-f relative_support`.

I don't really have a recommendation for more sensitive STAR alignment parameters. If you stick to the [recommended parameters](https://arriba.readthedocs.io/en/latest/workflow/), you should be good. You could increase the value of `--chimScoreDropMax` more, but it is already quite high.

If you only care about one particular virus or a handful of viruses, you can build an assembly containing only those and the human genome. Not having additional (non-relevant) viruses in the assembly reduces the risk of mismapping to a wrong genome.

If you truly don't care about false positives, you might as well choose a radical approach and extract everything from the discarded file affecting the viral contigs of interest. Or you may even go as far as to skip Arriba altogether and extract split reads/discordant mates directly from the BAM file and annotate them with a tool such as bedtools.

Do you want to share some of your synthetic files with me? It's hard to tell what would yield the best improvement without being able to take a look at the raw data to see which reads are missing. Not only would I be able to give you more qualified feedback, this could be an educational experience for myself, because I might learn something about current blind spots of Arriba with respect to viral detection.

That being said, you should always be careful not to overinterpret benchmarks based on synthetic data. It depends a lot on how the data were generated an how realistically they reproduce the true biological nature of viral integration. I have seem time and again that tools perform very differently on simulated vs. real data.

**Comment by suhrig** [comment] 2022-04-14 22:00
I'm closing this issue for now. If you still need further advice, feel free to reopen. And if you want to share your simulated data with me, I will gladly take a look at it.

**Closed by suhrig** 2022-04-14 22:00 UTC
