### ISSUE TITLE
download_references.sh hs37d5viral+GENCODE19 problem!

### ISSUE THREAD

**Issue by ppxinyi** [suhrig/arriba#249] opened 2024-08-28 03:30 UTC
export PATH=/scratch/chadbren_root/chadbren99/ppxinyi/STAR-2.7.11b/bin/Linux_x86_64/:$PATH
which STAR
/scratch/chadbren_root/chadbren99/ppxinyi/STAR-2.7.11b/bin/Linux_x86_64/STAR

./download_references.sh hs37d5viral+GENCODE19
Downloading assembly: http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz
Appending RefSeq viral genomes
Downloading annotation: http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/gencode.v19.annotation.gtf.gz
STAR: /lib64/libm.so.6: version GLIBC_2.29' not found (required by STAR)
STAR: /lib64/libstdc++.so.6: version GLIBCXX_3.4.26' not found (required by STAR)

I have try the git version but it still show the same error. Do i miss some import steps before?

**Comment by suhrig** [comment] 2024-08-28 09:42
This is an issue with STAR. Your STAR installation is not compatible with your operating system version. You need to recompile STAR rather than using the precompiled version which comes with the STAR download. Here is how:

```
wget https://github.com/alexdobin/STAR/archive/refs/tags/2.7.11b.tar.gz
tar -xf 2.7.11b.tar.gz
cd STAR-2.7.11b/source/
make
export PATH="$PWD:$PATH" # or: sudo cp -p STAR /usr/local/bin/
```

Alternatively, you can install Arriba via conda [as detailed in the manual](https://arriba.readthedocs.io/en/latest/quickstart/#installation-using-bioconda). In this case, a compatible version of STAR will be installed automatically.

**Comment by ppxinyi** [comment] 2024-08-29 00:20
> This is an issue with STAR. Your STAR installation is not compatible with your operating system version. You need to recompile STAR rather than using the precompiled version which comes with the STAR download. Here is how:
> 
> ```
> cd /scratch/chadbren_root/chadbren99/ppxinyi/STAR-2.7.11b/source/
> make
> export PATH="$PWD:$PATH"
> ```
> 
> Alternatively, you can install Arriba via conda [as detailed in the manual](https://arriba.readthedocs.io/en/latest/quickstart/#installation-using-bioconda). In this case, a compatible version of STAR will be installed automatically.

for the code you give I tried, it still show the same error:
 ./download_references.sh hs37d5viral+GENCODE19
Downloading assembly: http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz
Appending RefSeq viral genomes
Indexing assembly
Downloading annotation: http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/gencode.v19.annotation.gtf.gz
        STAR --runMode genomeGenerate --genomeDir STAR_index_hs37d5viral_GENCODE19 --genomeFastaFiles hs37d5viral.fa --sjdbGTFfile GENCODE19.gtf --runThreadN 8 --sjdbOverhang 250
        STAR version: 2.7.11b   compiled: 2024-08-28T19:55:43-04:00 gl-login2.arc-ts.umich.edu:/gpfs/accounts/chadbren_root/chadbren99/ppxinyi/STAR-2.7.11b/source
Aug 28 20:19:08 ..... started STAR run
Aug 28 20:19:08 ... starting to generate Genome files
./download_references.sh: line 162: 741383 Killed                  STAR --runMode genomeGenerate --genomeDir STAR_index_${ASSEMBLY}${VIRAL}_${ANNOTATION} --genomeFastaFiles "$ASSEMBLY$VIRAL.fa" --sjdbGTFfile "$ANNOTATION.gtf" --runThreadN "$THREADS" --sjdbOverhang "$SJDBOVERHANG"


for the conda method I think I meet the same problem:
/home/ppxinyi/miniforge3/var/lib/arriba/download_references.sh hs37d5viral+GENCODE19
Downloading assembly: http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz                                                                                                               
Appending RefSeq viral genomes
Indexing assembly
Downloading annotation: http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/gencode.v19.annotation.gtf.gz
        /home/ppxinyi/miniforge3/bin/STAR-avx2 --runMode genomeGenerate --genomeDir STAR_index_hs37d5viral_GENCODE19 --genomeFastaFiles hs37d5viral.fa --sjdbGTFfile GENCODE19.gtf --runThreadN 8 --sjdbOverhang 250
        STAR version: 2.7.11b   compiled: 2024-07-03T14:39:20+0000 :/opt/conda/conda-bld/star_1720017372352/work/source
Aug 28 19:52:39 ..... started STAR run
Aug 28 19:52:39 ... starting to generate Genome files
/home/ppxinyi/miniforge3/bin/STAR: line 8: 703850 Killed                  "${cmd}" "$@"

do you have any other method?

**Comment by suhrig** [comment] 2024-08-29 07:00
Both of my suggested methods worked. The error message is a different one now (`./download_references.sh: line 162: 741383 Killed` instead of `GLIBCXX_3.4.26' not found`). This means that STAR succeeded to start, because it is now compatible with your operating system.

The error you're now seeing is caused by STAR running out of memory. STAR needs around 40-60GB of memory to run. Do you have the ability to run this in a larger machine? If not, there is a way to run STAR with smaller memory requirements at the expense of longer runtimes. However, it will still need some 20-30GB.

**Closed** 2024-10-11 13:46 UTC
