### ISSUE TITLE
Error: Too many contigs

### ISSUE THREAD

**Issue by starz77** [suhrig/arriba#110] opened 2021-04-14 05:49 UTC
Hello,

here's my command

$DIR/arriba -x $INPUT/$1/$i"Aligned.toTranscriptome.out.bam" \
       -g $DIR/GENCODE19.gtf -a $DIR/hs37d5viral.fa \
       -o $OUTPUT/$i"_fusions.tsv" \
       -f blacklist

and Error occurred

Reading chimeric alignments from '$DIR/$iAligned.toTranscriptome.out.bam' ERROR: too many contigs

why does this happen?

thank you.

**Comment by suhrig** [comment] 2021-04-14 11:02
Hello,

You must align the reads to the genome, not to the transcriptome. That's the problem. You can find the recommended STAR alignment parameters in the manual: https://arriba.readthedocs.io/en/latest/workflow/#demo-script

Is there a particular reason why you disable the blacklist? There will be many more false positives without the blacklist.

Regards,
Sebastian

**Comment by starz77** [comment] 2021-04-15 06:05
Hello

I tried running STAR with the recommended script.

But, It doesn't work well.

'$#%%%"""NHCHICASCnMCm^cdmuSRR949087.3052829@(D"!DD$"B""!"("!""""AHDA!B"("(B("""%%%%%'''''(()))())))))()))))))))))))())))())''%'%%%%%$$$#$###### !##HCHICASCnMCm^dmSRR949087.3052829@BAB!D"!"""(AB("!B!!!DD(!"(""!(D$!("#"! !!NHCHICASCnMCHMdSRR949087.3052830HA!HD!A(D!(BAA!(HDA!BA"""%%%%%''''')'()()())))))))))))()&()(()))))))))))(()))))))))))(()))())''()&#'&'''%%%%%#$"#$ ##!"##NHCHICASC'nMCuTA1HdSRR949087.3052830($AA(!""B"(!HD("!HH(!!%%%%%''''')))))()()%)()))))))))))))))())()))))()))))()((()&()(^C

There're Error messages like above.

thank you.

**Comment by suhrig** [comment] 2021-04-15 06:39
This looks like content from the FastQ files. I don't really have an idea why it is printed to the terminal. Can you post the following details, please, to help me debug the issue:

1. What is the exact command you use to run `run_arriba.sh`?
2. Maybe the script was corrupted during the download. What is the output of `md5sum run_arriba.sh`?
3. What is the version of bash that you are using `bash --version`?
4. What is your version of STAR `STAR --version`?
5. Which Linux version do you use (Ubuntu 20.04, CentOS 7.9, ...)?

**Comment by starz77** [comment] 2021-04-15 06:46
maybe errors came from STAR.

my answer

1.

#!/bin/bash
INPUT=/bio/scratch/starz77/Prospective_NGS/public_AML/LeuceGene/RNA/STAR
OUTPUT=/bio/scratch/starz77/Prospective_NGS/public_AML/LeuceGene/RNA/Fusion/Arriba
DIR=/bio/scratch/starz77/Tools/arriba_v2.1.0
i=$1

$DIR/arriba -x $INPUT/$i/$i".bam" \
       -g $DIR/GENCODE19.gtf -a $DIR/hs37d5viral.fa \
       -o $OUTPUT/$i"_fusions.tsv" \
       -b $DIR/database/blacklist_hg19_hs37d5_GRCh37_v2.1.0.tsv.gz
2.
351b69ecf9d3d7d53d887d216ac7ea18  run_arriba.sh

3,
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

4.
2.7.8a


5.
NAME="Scientific Linux"
VERSION="7.6 (Nitrogen)"


Thank you.

**Comment by suhrig** [comment] 2021-04-15 07:06
Thanks for the details, I can try to reproduce the issue.

I think you misunderstood question 1. I was asking about the command to run the script `run_arriba.sh`, not about your custom command to run the `arriba` executable. You wrote that the recommended script does not work. I assume by "recommended script" you meant `run_arriba.sh`, right? And the cryptic error message is from the script `run_arriba.sh`, not from your custom command, right?

**Comment by starz77** [comment] 2021-04-15 07:51
I think some problems with my method.

"run_arriba.sh" that you talking about is "$MY_DIR/arriba_v2.1.0/run_arriba.sh".

But I'm running STAR and Arriba on my own bash script.

The name of my script was also "run_arriba.sh".

I checked "your" run_arriba.sh and changed arguments.

Finally, it worked.

Sorry for the misunderstanding.

Thank you for your fascinating Tool and your kindness.

**Comment by suhrig** [comment] 2021-04-15 07:54
> The name of my script was also "run_arriba.sh".

Haha, that is a funny coincidence/misunderstanding. :-D

Glad you figured it out in the end. I'm closing the issue for now. Feel free to come back if you have more questions.

**Closed by suhrig** 2021-04-15 07:54 UTC
