### ISSUE TITLE
GTF file malformed (Arriba)

### ISSUE THREAD

**Issue by Smartmandm** [suhrig/arriba#48] opened 2020-02-24 00:22 UTC
Hello,

I want to run Arriba directly (without STAR) because I already have the bam file of my rna-seq sample. When inputting the necessary files in the  command line (/.arriba   .bam file, .gtf file, .fa file, etc) , when I run the analysis each time it says that my GTF file is malformed  - I have also tried the GTF file (assembly) from your script "download_references.sh" - which does not work either : 

ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/gencode.v19.annotation.gtf.gz

BTW I'm running Arriba on Mac .

Thank you!

Marie

**Comment by Smartmandm** [comment] 2020-02-24 00:56
I meant annotation, not assembly.

**Comment by suhrig** [comment] 2020-02-24 09:21
Hi Marie,

This might be a duplicate of #37. Apparently on Mac, uncompressed text files fail to load, because Mac interprets a certain C function differently than on Linux. You need to pass the file in gzipped format. Different code is used to load gzipped files and that code works on Linux and Mac alike. The same is true for the assembly file and any other plain text file BTW.

Sorry for this inconvenience. But Mac has not been officially supported so far. (Where are all the Mac users coming from all of a sudden? :-D) It will be with the next release and then loading of text files will work. If you notice any other strange behavior on Mac, let me know. I'm interested in feedback, because I don't have a good test environment for Mac myself.

One more note: When you run Arriba on preexisting BAMs, STAR must have been run with the parameters `- - chimSegmentMin` and `--chimOutType` set to `WithinBAM` or `SeparateSAMold`. Otherwise, the BAMs do not contain chimeric alignments. 

Regards,
Sebastian

**Comment by CarmenBugarin** [comment] 2020-07-01 20:59
Hi,

I am having exactly the same issue

`ERROR: Malformed GTF features: /users/xxx/anaconda3/envs/arriba/var/lib/arriba/GENCODE28.gtf.gz
Error in parseFileParameter("fusions", args, T) : `

However, I am running Arriba in a linux HPC system using anaconda3. The weirdest thing is that I have run some samples using the exactly same scripts before and they worked fine.

Any suggestion??

Many thanks!
Carmen

**Comment by suhrig** [comment] 2020-07-01 21:17
Hi Carmen,

If I'm interpreting the error message correctly, Arriba was run with `-G .../GENCODE28.gtf.gz` instead of `-g .../GENCODE28.gtf.gz`. Are you using the `run_arriba.sh` script? Or do you call `arriba` directly? Can you paste the full `arriba` command, please?

Thanks,
Sebastian

**Comment by CarmenBugarin** [comment] 2020-07-01 21:21
Hi Sebastian, 

Thanks for the quick reply. 

I have tried using -G and -g zipping the GENCODE28 file.

`#!/bin/bash -l
#SBATCH --job-name=arriba                         
#SBATCH --nodes=1                                    
#SBATCH --ntasks=16                                    
#SBATCH --partition xxx                              
#SBATCH --mem=30G


source /users/xxx/anaconda3/bin/activate arriba

arriba -x /scratch/users/xxx/RNA_seq/bams/$1Aligned.sortedByCoord.out.bam -T -P -I \
-G /users/xxx/anaconda3/envs/arriba/var/lib/arriba/GENCODE28.gtf.gz \
-a /users/xxx/anaconda3/envs/arriba/var/lib/arriba/hg38.fa \
-b /users/xxx/anaconda3/envs/arriba/var/lib/arriba/blacklist_hg38_GRCh38_2018-11-04.tsv.gz  \
-o /scratch/users/xxx/RNA_seq/output/$1.tsv -O /scratch/users/xxx/RNA_seq/output/$1.discarded.tsv



##########################################
### Drawing translocations
##########################################


./draw_fusions.R \
--fusions=/scratch/users/xxx/RNA_seq/output/$1.tsv \
--alignments=/scratch/users/xxx/RNA_seq/bams/$1Aligned.sortedByCoord.out.bam  \
--output=/scratch/users/xxx/RNA_seq/Fusions/$1.pdf \
--annotation=/users/xxx/anaconda3/envs/arriba/var/lib/arriba/GENCODE28.gtf \
--cytobands=/users/xxx/anaconda3/envs/arriba/var/lib/arriba/cytobands_hg38_GRCh38_2018-02-23.tsv \
--proteinDomains=/users/xxx/anaconda3/envs/arriba/var/lib/arriba/protein_domains_hg38_GRCh38_2019-07-05.gff3`

**Comment by suhrig** [comment] 2020-07-01 21:41
> I have tried using -G and -g

You definitely have to use lowercase `-g`. What was the error message when you used lowercase `-g`?

**Comment by CarmenBugarin** [comment] 2020-07-01 22:03
`ERROR: could not find sequence of contig '10'
Error in parseFileParameter("fusions", args, T) : 
  Cannot read file: /scratch/users/xxx/RNA_seq/output/result.tsv
Execution halted
`

**Comment by suhrig** [comment] 2020-07-02 10:02
This is the same issue as in #37. On some systems (so far I was only aware of Mac), plain text files are not loaded, because the system reports them as empty. Gzipped files are not affected, because different code is used to load them. Sorry for the inconvenience.

You have two options:
1. Gzip the FastA file, too.
2. Download and compile the current `develop` version of Arriba.

**Comment by suhrig** [comment] 2020-10-10 19:08
Dear Marie and Carmen,

[Arriba 2.0.0 is out](https://github.com/suhrig/arriba/releases/tag/v2.0.0). It no longer suffers from the bug that on some systems GTF files cannot be read unless they are gzipped. So your issues should be resolved. I am closing this issue, hence. Feel free to reopen if you still have problems.

Regards,
Sebastian

**Closed by suhrig** 2020-10-10 19:08 UTC
